JBIDE-28740 - Update WildFly to version 27 in examples.itests
jbosstools/jbosstools-integration-tests pull request #2065
Opened 2022-11-17 01:02 UTC by zcervink

JIRA: https://issues.redhat.com/browse/JBIDE-28740
Jenkins: to be added soon

2022-11-17 02:39 UTC, zcervink commented
@odockal please review

2022-11-24 09:56 UTC, odockal requested changes

2022-11-24 09:56 UTC, odockal commented on tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
> +		".*The import jakarta.jws cannot be resolved.*",
Aren't these more likely bugs? Are they reported?

2022-11-24 10:40 UTC, zcervink commented on tests/org.jboss.tools.examples.ui.bot.test/resources/servers/wildfly-blacklist-test-errors-regexes.json
> +		".*The import jakarta.jws cannot be resolved.*",
@odockal Reported here: https://issues.redhat.com/browse/JBIDE-28793

2022-11-29 13:22 UTC, odockal approved these changes

2022-11-29 13:22 UTC, merged